#!/bin/bash

tmpdir=$(mktemp -d)
cd $tmpdir
printf "package main;func main(){\nfmt.Println(\"letsgo\");}" > default.go
goimports -w default.go
vim -u NONE --noplugin default.go
goimports -w default.go
go run default.go | less -X
while true; do
    cat default.go
    echo
    echo "your file is here:"
    echo $tmpdir/default.go
    echo "[r]un again [e]dit [s]hare [q]uit"
    read -s -n 1 whatdo
    case $whatdo in
        r|R) 
            # echo "would go run" 
            printf '\033[2J'
            go run default.go | less -X 
            ;;
        e|E) 
            # echo "would give 'em vim"  
            printf '\033[2J'
            vim -u NONE --noplugin default.go 
            goimports -w default.go
            go run default.go | less -X
            ;;
        s|S)
            echo "https://play.golang.org/p/"`curl -s -X POST https://play.golang.org/share --data-binary '@default.go'`
            break
            ;;
        q|Q) 
            echo "later."
            break 
            ;;
        *) 
            echo "Hey, don't be upset ʕ◔ϖ◔ʔ"; 
            break 
            ;;
    esac
done
